### ISSUE TITLE
CoverTree out of bound

### ISSUE THREAD

**Issue by d8w** [autonlab/fastlvm#6]
## Reproduce the error
Run `test_coverTree.py` in `tests`
```
Error
Traceback (most recent call last):
  File "/data/apps/anaconda3/envs/d3m/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/data/apps/anaconda3/envs/d3m/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/dwang/sandbox/d3m.ta1/fastlvm/tests/test_coverTree.py", line 61, in test_produce_3nn
    first, second = self.run_models(3)
  File "/home/dwang/sandbox/d3m.ta1/fastlvm/tests/test_coverTree.py", line 38, in run_models
    first = np.squeeze(self.x[a.value])
IndexError: index 21986 is out of bounds for axis 0 with size 1000
```

**Comment by d8w** [comment]
The UID  at the following line may be corrupted. 
https://github.com/autonlab/fastlvm/blob/6f9b45dc5254e506359741aca4544dae5087712b/src/cover_tree/cover_tree.h#L70
