### ISSUE TITLE
GMM results differ widely from baseline

### ISSUE THREAD

**Issue by d8w** [autonlab/fastlvm#7]
## To reproduce, run `test_produce` in `test_GMM.py`
```
Failure
Traceback (most recent call last):
  File "/data/apps/anaconda3/envs/d3m/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/data/apps/anaconda3/envs/d3m/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/dwang/sandbox/d3m.ta1/fastlvm/tests/test_GMM.py", line 35, in test_produce
    self.assertAlmostEqual(a, b)
  File "/data/apps/anaconda3/envs/d3m/lib/python3.6/unittest/case.py", line 878, in assertAlmostEqual
    raise self.failureException(msg)
AssertionError: -2645.3270294950835 != -1431.277959894651 within 7 places
```

**Comment by d8w** [comment]
The scores are log likelihood. Their corresponding likelihood are close to zero. I'm not sure if the comparison is a good idea. Close for now.
